variable subscription_id {}
variable client_id {}
variable client_secret {}
variable tenant_id {}
variable location {}
variable "virtual_network_name" {}
variable ressource_group_name {}
variable virtual_network_address_space {}
variable subnet_name {}
variable subnet_address_space {}
variable public_ip_name {}
variable allocation_method {}
variable network_interface_name {}
variable ip_configuration_name {}
variable managed_disk_name {}
variable managed_disk_sizeGB {}
variable managed_disk_lun {}
variable disk_type {}
variable disk_option {}
variable vm_name {}
variable vm_size {}
variable os_disk_name {}
variable disk_caching {}
variable os_option {}
variable storage_disk_name {}
variable storage_disk_sizeGB {}
variable storage_disk_lun {}
variable publisher {}
variable offer {}
variable sku {}
variable os_version {}
variable login {}
variable password {}